server:
  port: 8080

spring:
  datasource:
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/farm_plus?useUnicode=true&characterEncoding=UTF-8
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  logging:
    level:
      io.netty.resolver.dns: DEBUG

jwt:
  secret: your-secret-key-here  # JWT 비밀키 추가
  expiration: 86400000            # JWT 만료 시간 (예: 1일)
