server:
  port: 8080

spring:
  datasource:
    username: ${USERNAME}
    password: ${PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://database-1.cvo0mcig6l5w.ap-northeast-2.rds.amazonaws.com:3306/farm_plus?useUnicode=true&characterEncoding=UTF-8
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
  logging:
    level:
      io.netty.resolver.dns: DEBUG

jwt:
  secret-key-source: ${SECRETKEY}  # JWT 비밀키

security:
  oauth2:
    client:
      registration:
        kakao:
          client-id: YOUR_KAKAO_REST_API_KEY  # 카카오 REST API 키
          client-authentication-method: post
          authorization-grant-type: authorization_code
          redirect-uri: "{baseUrl}/auth/kakao/callback"
          scope: profile_nickname, account_email
      provider:
        kakao:
          authorization-uri: https://kauth.kakao.com/oauth/authorize
          token-uri: https://kauth.kakao.com/oauth/token
          user-info-uri: https://kapi.kakao.com/v2/user/me


gradle:
  java:
    home: "/usr/lib/jvm/java-17-openjdk-amd64"